#!/usr/bin/env bash

###############################################################################
# .shenv
###############################################################################

# Load environment if it hasn't already been.
if [[ "${SHENV_LOADED}" != true ]]; then
  source "${HOME}/.shenv"
fi

################# BASH Configuration #################

# Path to the bash it configuration
export BASH_IT="${HOME}/.bash_it"

# clone bash-it to home folder && install if not found
if [[ ! -d $BASH_IT ]]; then
  git clone --depth=1 https://github.com/Bash-it/bash-it.git ~/.bash_it && ~/.bash_it/install.sh
fi

# Lock and Load a custom theme file
# location /.bash_it/themes/
export BASH_IT_THEME='agnoster'

# Don't check mail when opening terminal.
unset MAILCHECK

# Change this to your console based IRC client of choice.
export IRC_CLIENT='irssi'

# Set this to the command you use for todo.txt-cli
export TODO="todo"

# Set this to false to turn off version control status checking within the prompt for all themes
export SCM_CHECK=true

# Set Xterm/screen/Tmux title with only a short hostname.
# Uncomment this (or set SHORT_HOSTNAME to something else),
# Will otherwise fall back on $HOSTNAME.
export SHORT_HOSTNAME=$(hostname -s)

# Set Xterm/screen/Tmux title with only a short username.
# Uncomment this (or set SHORT_USER to something else),
# Will otherwise fall back on $USER.
export SHORT_USER=${USER:0:9}

# Set Xterm/screen/Tmux title with shortened command and directory.
# Uncomment this to set.
export SHORT_TERM_LINE=true

# Set vcprompt executable path for scm advance info in prompt (demula theme)
# https://github.com/djl/vcprompt
#export VCPROMPT_EXECUTABLE=~/.vcprompt/bin/vcprompt

# (Advanced): Uncomment this to make Bash-it reload itself automatically
# after enabling or disabling aliases, plugins, and completions.
export BASH_IT_AUTOMATIC_RELOAD_AFTER_CONFIG_CHANGE=1

# Load Bash It
source "${BASH_IT}/bash_it.sh"

# load fzf
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# integrate iterm
test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

# enable brew-file
if [ -f $(brew --prefix)/etc/brew-wrap ];then
  source $(brew --prefix)/etc/brew-wrap
fi

# enable asdf
source ${HOME}/.asdf/asdf.sh
source ${HOME}/.asdf/etc/bash_completion.d/asdf.bash

